### PR TITLE
Update nextjs-sdk.mdx

### PR DESCRIPTION
**Pull request by yyaskriloff**
Use Kinde Management API which would help with having so many env vars

#### Related issues & labels (optional)

- Closes #
- Suggested label: 

## Summary by CodeRabbit

- **New Features**
	- Expanded documentation on integrating Kinde authentication with the Next.js App Router SDK.
	- Added detailed instructions for setting up callback URLs and environment variables.
	- Introduced examples for user authentication processes, including sign-up, sign-in, and logout functionalities.

- **Documentation**
	- Clarified handling of authentication states and route protection.
	- Updated migration guide to reflect changes in function behavior for `getKindeServerSession`.

### CODE REVIEW

**Comment by marcosmartini** [comment]
Hey @yyaskriloff, thanks for your contribution  🙌  and sorry for the late reply.

If I understand correctly, you're suggesting using the `@kinde/management-api-js` package in order to avoid some extra environment variables, is that right?

If that's the case, remember that `@kinde/management-api-js` requires [3 environment variables](https://github.com/kinde-oss/management-api-js?tab=readme-ov-file#configuration) to work, so we would still need those — in fact I guess an extra one, which would be a duplicate in this case since `KINDE_ISSUER_URL` would be the same as `KINDE_DOMAIN`, and also the project would have an extra dependency. 

Do you think we should add this step with the `@kinde/management-api-js` alongside the original example? 

Happy to hear your thoughts.

Cheers,
Marcos.

**Comment by yyaskriloff** [comment]
@marcosmartini Adding it along side makes sense. I'm already using the '@kinde/management-api-js' in my project but if I wasn't you're right it would be an extra dependency.

**Comment by yyaskriloff** [comment]
I can write something up I'm not available at the moment but I'll try in the coming days.

**Comment by marcosmartini** [comment]
Thanks @yyaskriloff! I'll update the branch to `draft` for now.

**Comment by marcosmartini** [comment]
Closing this one now @yyaskriloff - I've added a note to the Next.js docs in #262 - Thanks!

**Pull request closed without merging**
